### ISSUE TITLE
[에러] travis-ci 빌드 에러 - node_modules/karma/bin/karma: No such file or directory

### ISSUE THREAD

**Issue by nypark425** [nypark425/ECMAScript6#1]
<img width="1296" alt="2017-07-03 12 02 33" src="https://user-images.githubusercontent.com/10542786/27771088-fd2ca2f4-5f82-11e7-965c-4f360b05929f.png">

**문제**
- node_modules 폴더가 gitignore에 걸려서 repository에 없기 때문?
- .travis.yml의 설정파일에는 `node_modules/karma/bin/karma`를 사용하라는데, 어떡해야하지?

**.travis.yml**

```YAML
language: node_js
node_js:
  - "6"
install:
  - npm install
before_script: cd travis-test
script: node_modules/karma/bin/karma start --single-run --browsers PhantomJS
```
